name: Using Deb

on:
  push:
  workflow_dispatch:
    inputs:
      drwaio:
        description: 'Run tests'
        required: false
        default: 'OK'

env:
  DISPLAY: :99.0
  DRAWIO_VERSION: 13.9.9
  DRAWIO_DISABLE_UPDATE: true

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Instaling drawio
        run: |
          sudo apt-get install libappindicator3-1
          wget https://github.com/jgraph/drawio-desktop/releases/download/v${{ env.DRAWIO_VERSION }}/draw.io-amd64-${{ env.DRAWIO_VERSION }}.deb
          sudo dpkg -i draw.io-amd64-${{ env.DRAWIO_VERSION }}.deb
          sudo rm draw.io-amd64-${{ env.DRAWIO_VERSION }}.deb
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - name: get help
        run: |
          drawio --help
          drawio -V
