name: Using Snap

on:
  push:
  workflow_dispatch:
    inputs:
      drwaio:
        description: 'Run tests'
        required: false
        default: 'OK'

env:
  DRAWIO_DISABLE_UPDATE: true
  DRAWIO_ENV: dev
  DISPLAY: :99.0
  DRAWIO_VERSION: 13.9.9

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Instaling drawio
        timeout-minutes: 3
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sudo apt-get install libappindicator3-1
          sudo snap install drawio
          drawio --help
