name: Draw.io Compiler

on: 
  workflow_dispatch:
    inputs:
      drwaio:
        description: 'Run tests'     
        required: false
        default: 'OK'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Instaling drawio
        timeout-minutes: 3
        run: |
          sudo snap install drawio
          drawio --help