name: Using Snap

on:
  workflow_dispatch:
    inputs:
      drwaio:
        description: 'Run tests'
        required: false
        default: 'OK'

env:
  DRAWIO_DISABLE_UPDATE: true
  DRAWIO_ENV: dev

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Instaling drawio
        timeout-minutes: 3
        run: |
          sudo snap install drawio
          drawio --help
